// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_volunteer.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmXdr9kgx7gddUvlidV_Q6YGGiHZn6x0g',
    appId: '1:669877574860:web:a5c729ec86318c2ebcf669',
    messagingSenderId: '669877574860',
    projectId: 'sahaya-7df6d',
    authDomain: 'sahaya-7df6d.firebaseapp.com',
    storageBucket: 'sahaya-7df6d.firebasestorage.app',
    measurementId: 'G-HWYTY3L0W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8gF0zO_LqhQCzfgXgu-GmINlrI0EtrE',
    appId: '1:669877574860:android:0a47063cf4592cadbcf669',
    messagingSenderId: '669877574860',
    projectId: 'sahaya-7df6d',
    storageBucket: 'sahaya-7df6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABpMhghYxOr1O8z75Q2lMEF8vrlBt3veM',
    appId: '1:669877574860:ios:c579bfb267e079dabcf669',
    messagingSenderId: '669877574860',
    projectId: 'sahaya-7df6d',
    storageBucket: 'sahaya-7df6d.firebasestorage.app',
    iosBundleId: 'com.sahaya.volunteer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABpMhghYxOr1O8z75Q2lMEF8vrlBt3veM',
    appId: '1:669877574860:ios:419205deddee9ef1bcf669',
    messagingSenderId: '669877574860',
    projectId: 'sahaya-7df6d',
    storageBucket: 'sahaya-7df6d.firebasestorage.app',
    iosBundleId: 'com.sahaya.sahaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmXdr9kgx7gddUvlidV_Q6YGGiHZn6x0g',
    appId: '1:669877574860:web:3d37440501fd1b92bcf669',
    messagingSenderId: '669877574860',
    projectId: 'sahaya-7df6d',
    authDomain: 'sahaya-7df6d.firebaseapp.com',
    storageBucket: 'sahaya-7df6d.firebasestorage.app',
    measurementId: 'G-R9PVV7M7SJ',
  );
}
